# Generated by Django 4.1.5 on 2023-01-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('matiere', models.CharField(choices=[('MATHS', 'MATHS'), ('PC', 'PC'), ('SVT', 'SVT'), ('FRAN', 'FRAN'), ('ANG', 'ANG'), ('HG', 'HG'), ('PHILO', 'PHILO'), ('ALL', 'ALL'), ('ESPA', 'ESPA'), ('EDHC', 'EDHC'), ('INFO', 'INFO'), ('EPS', 'EPS')], max_length=200, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
