# Generated by Django 4.1.5 on 2023-01-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0002_rename_administrations_administration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administration',
            name='matiere',
        ),
        migrations.AddField(
            model_name='administration',
            name='fonction',
            field=models.CharField(choices=[('Educateur', 'Educateur'), ('Caissière', 'Caissière'), ('Stagiaire', 'Stagiaire'), ('Gardiennage', 'Gardiennage')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='administration',
            name='telephone',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
