# Generated by Django 4.1.5 on 2023-01-26 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0003_remove_administration_matiere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administration',
            name='telephone',
        ),
    ]
