# Generated by Django 4.1.5 on 2023-01-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0004_remove_administration_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administration',
            old_name='date_creation',
            new_name='emargement',
        ),
        migrations.AlterField(
            model_name='administration',
            name='fonction',
            field=models.CharField(choices=[('MATHS', 'MATHS'), ('PC', 'PC'), ('SVT', 'SVT'), ('FRAN', 'FRAN'), ('ANG', 'ANG'), ('HG', 'HG'), ('PHILO', 'PHILO'), ('ALL', 'ALL'), ('ESPA', 'ESPA'), ('EDHC', 'EDHC'), ('INFO', 'INFO'), ('EPS', 'EPS'), ('Educateur', 'Educateur'), ('Caissière', 'Caissière'), ('Stagiaire', 'Stagiaire'), ('Gardiennage', 'Gardiennage')], max_length=200, null=True),
        ),
    ]
