# Generated by Django 4.1.5 on 2023-01-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0005_rename_date_creation_administration_emargement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administration',
            name='emargement',
        ),
        migrations.AddField(
            model_name='administration',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='administration',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='administration',
            name='fonction',
            field=models.CharField(choices=[(' PROF:MATHS', 'PROF:MATHS'), ('PROF:PC', 'PROF:PC'), ('PROF:SVT', 'PROF:SVT'), ('PROF:FRAN', 'PROF:FRAN'), ('PROF:ANG', 'PROF:ANG'), ('PROF:HG', 'PROF:HG'), ('PROF:PHILO', 'PROF:PHILO'), ('PROF:ALL', 'PROF:ALL'), ('PROF:ESPA', 'PROF:ESPA'), ('PROF:EDHC', 'PROF:EDHC'), ('PROF:INFO', 'PROF:INFO'), ('PROF:EPS', 'PROF:EPS'), ('Enseign:CP1', 'Enseign:CP1'), ('Enseign:CP2', 'Enseign:CP2'), ('Enseign:CE1', 'Enseign:CE1'), ('Enseign:CE2', 'Enseign:CE2'), ('Enseign:CM1', 'Enseign:CM1'), ('Enseign:CM2', 'Enseign:CM2'), ('Educateur', 'Educateur'), ('Caissière', 'Caissière'), ('Stagiaire', 'Stagiaire'), ('Gardiennage', 'Gardiennage')], max_length=200, null=True),
        ),
    ]
