# Generated by Django 4.1.5 on 2023-02-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emarge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emarge',
            name='fonction',
            field=models.CharField(choices=[('MATHS', 'MATHS'), ('PC', 'PC'), ('SVT', 'SVT'), ('FRAN', 'FRAN'), ('ANG', 'ANG'), ('HG', 'HG'), ('PHILO', 'PHILO'), ('ALL', 'ALL'), ('ESPA', 'ESPA'), ('EDHC', 'EDHC'), ('INFO', 'INFO'), ('EPS', 'EPS'), ('PRIMAIRE', 'PRIMAIRE'), ('Educateur', 'Educateur'), ('Caissière', 'Caissière'), ('Stagiaire', 'Stagiaire'), ('Gardiennage', 'Gardiennage')], max_length=200, null=True),
        ),
    ]
