# Generated by Django 4.1.5 on 2023-04-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emarge', '0002_alter_emarge_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='emarge',
            name='Nombre_d_heures',
            field=models.CharField(choices=[('OK', 'OK'), ('Absent', 'Absent'), ('2heures', '2heures'), ('3heures', '3heures'), ('4heures', '4heures'), ('5heures', '5heures'), ('6heures', '6heures'), ('7heures', '7heures'), ('8heures', '8heures'), ('9heures', '9heures'), ('10heures', '10heures')], max_length=12, null=True),
        ),
    ]
