# Generated by Django 4.1.5 on 2023-10-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emarge', '0004_rename_nombre_d_heures_emarge_nombre_d_heures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emarge',
            name='fonction',
            field=models.CharField(choices=[('MATHS', 'MATHS'), ('PC', 'PC'), ('SVT', 'SVT'), ('FRAN', 'FRAN'), ('ANG', 'ANG'), ('HG', 'HG'), ('PHILO', 'PHILO'), ('ALL', 'ALL'), ('ESPA', 'ESPA'), ('EDHC', 'EDHC'), ('INFO', 'INFO'), ('EPS', 'EPS'), ('PRIMAIRE', 'PRIMAIRE'), ('Educateur', 'Educateur'), ('Directeur', 'Directeur'), ('Caissière', 'Caissière'), ('Stagiaire', 'Stagiaire'), ('Gardiennage', 'Gardiennage')], max_length=200, null=True),
        ),
    ]
