# Generated by Django 4.1.5 on 2023-01-26 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteurs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instituteurs',
            new_name='Instituteur',
        ),
    ]
