# Generated by Django 4.1.5 on 2023-01-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteurs', '0002_rename_instituteurs_instituteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituteur',
            name='matiere',
        ),
        migrations.AddField(
            model_name='instituteur',
            name='classe',
            field=models.CharField(choices=[('CP1', 'CP1'), ('CP2', 'CP2'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2')], max_length=200, null=True),
        ),
    ]
