# Generated by Django 4.1.5 on 2023-01-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteurs', '0004_rename_date_creation_instituteur_annee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteur',
            name='annee',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instituteur',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
