# Generated by Django 4.1.5 on 2023-01-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0002_rename_professeurs_professeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
