# Generated by Django 4.1.5 on 2023-01-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0003_professeur_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professeur',
            old_name='date_creation',
            new_name='annee',
        ),
    ]
